### ISSUE TITLE
Enhance Load Balancer Configuration File Format

### ISSUE THREAD

**Issue by ardatosun** [ardatosun/loadbalancer#10]
Refactor the load balancer configuration file to support comments and improved readability. Consider adopting a standardized format (e.g., YAML) to enhance usability and make the configuration easier for users to understand.

#### Requirements:
- Implement parsing for the new format, ensuring backward compatibility if needed.
- Update the documentation to reflect the changes in the configuration format.
- Implement parsing for the new format, if needed.

**Comment by ohyesgocool** [comment]
Hi @ardatosun ,

Thanks for brining this up. I can pick this up. But perhaps could you please explain what all the configs atleast for now are we planning to migrate ? Could you point me the link to start with ?

I can do it in YAML itself , or if there is any other preference that you have , maybe we can discuss that too. 

WDYT ?

Thanks,

**Comment by ardatosun** [comment]
Hi @ohyesgocool,

Thank you for your interest. Currently the configurations that we do/could have are:
- Backend URLs
- Health check interval
- Max Latency
- Timeout for health check, retries
- Port

So I was thinking to move all/some of these to a config file such as YAML, instead of hardcoding or providing via environment variables. Something like this:

```yaml
backends:
  - url: http://backend1.example.com
  - url: http://backend2.example.com

health_check_interval: 30s  # Health check every 30 seconds
timeout: 2s                 # Timeout for each health check request
port: 8080                  # Port for the load balancer to listen on
```

Although having some of these (e.g. backend server address) as environment variables seems better to make it dynamic and to make it more production grade, I thought maybe we could move some config to yaml. At least not hardcoded in the go code.

Let me know your thoughts.
